# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalist',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='finalist',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
