# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20171125_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='user',
        ),
    ]
