# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_judge_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={},
        ),
        migrations.AlterModelManagers(
            name='judge',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='judge',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='email',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='password',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='username',
        ),
    ]
