# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20171125_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finalist',
        ),
        migrations.AddField(
            model_name='judge',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Judge man'),
        ),
    ]
